version: '3'

services:
  node:
    env_file:
      - .env
    image: quorumengineering/quorum:22.7.1
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./data:/data
      - ./keystore:/keystore:ro
    network_mode: host
    entrypoint: ["sh" ,"-c", /docker-entrypoint.sh]
