version: '3'

services:
  tailscale:
    image: tailscale/tailscale:v1.64
    hostname: tailscale-validator
    env_file:
      - .env
    volumes:
      - ${PWD}/tailscale-validator/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  node:
    env_file:
      - .env
    image: quorumengineering/quorum:22.7.1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./data:/data
      - ./keystore:/keystore:ro
    depends_on:
      - tailscale
    network_mode: service:tailscale
    entrypoint: /docker-entrypoint.sh
