geth \
--networkid ${NETWORKID} \
--gcmode archive \
--password ./keystore/accountPassword \
--keystore /keystore \
--permissioned \
--verbosity ${VERBOSITY} \
--datadir ./data \
--syncmode full \
--port 30303 \
--nousb \
--identity ${TS_HOSTNAME}-validator \
--nodekey ./keystore/nodekey \
--nodiscover \
--metrics \
--pprof \
--pprof.addr 127.0.0.1 \
--pprof.port 9545 \
--istanbul.blockperiod 5 \
--istanbul.requesttimeout 10000 \
--http \
--http.addr 127.0.0.1 \
--http.port 8545 \
--http.corsdomain '*' \
--http.vhosts '*' \
--http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,qbft \
--ws \
--ws.addr 127.0.0.1 \
--ws.port 8546 \
--ws.origins '*' \
--ws.rpcprefix '/' \
--ws.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,qbft init ./data/genesis.json

geth \
--networkid ${NETWORKID} \
--gcmode archive \
--password /keystore/accountPassword \
--keystore /keystore \
--permissioned \
--verbosity ${VERBOSITY} \
--datadir /data \
--syncmode full \
--port 30303 \
--nousb \
--identity ${TS_HOSTNAME}-validator \
--nodekey /keystore/nodekey \
--nodiscover \
--metrics \
--pprof \
--pprof.addr 127.0.0.1 \
--pprof.port 9545 \
--istanbul.blockperiod 5 \
--istanbul.requesttimeout 10000 \
--http \
--http.addr 127.0.0.1 \
--http.port 8545 \
--http.corsdomain '*' \
--http.vhosts '*' \
--http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,qbft \
--ws \
--ws.addr 127.0.0.1 \
--ws.port 8546 \
--ws.origins '*' \
--ws.rpcprefix '/' \
--ws.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,qbft`