version: '3'

services:
  node:
    image: quorumengineering/quorum:22.7.1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./data:/data
      - ./keystore:/keystore:ro
    entrypoint: /docker-entrypoint.sh
